### ISSUE TITLE
 Соотношения добавляемых компонентов TDS.

### ISSUE THREAD

**Issue by TremaUser1** [ezplant-file/ezplant#7]
Соотношения добавляемых компонентов TDS. Не уверен в правильности пропорции (смотрел по числу миганий курсора, так что могу ошибаться).  Отличия во времени работы есть, но такое ощущение, что не пропорциональные.

**Comment by drondistortion** [comment]
Нужны подробности: текущие настройки работы насосов

**Comment by drondistortion** [comment]
исправлено, неправильно (неявное округление преобразование float)
